"""Emit overleaf/figures/cascade.tex: the decoherence cascade as a band
chart. Shaded envelope = min-max across the 13 styles; bold line = mean;
open markers = noise-corrected means; squares = other encoders."""
import json
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORR = {"MLD": 0.162, "MDM": 0.102, "T2M-GPT": 0.009}
GCOL = {"MLD": "okskyblue", "MDM": "okgreen", "T2M-GPT": "okorange"}

def rep_styles(model):
    r = json.load(open(ROOT / f"results/{model}/report.json"))
    return {k: float(v) for k, v in r["consistency"].items()}

def gen_styles(model):
    ZS = np.stack([np.load(p / "Z_S.npy") for p in sorted(ROOT.glob(f"results/{model}/seed4*/0"))])
    ZT = np.stack([np.load(p / "Z_T.npy") for p in sorted(ROOT.glob(f"results/{model}/seed4*/0"))])
    meta = json.load(open(next(ROOT.glob(f"results/{model}/seed4*/0")) / "meta.json"))
    d = (ZT - ZS[:, None]).mean(0)
    out = {}
    for j, s in enumerate(meta["styles"]):
        v = d[j] / (np.linalg.norm(d[j], axis=-1, keepdims=True) + 1e-9)
        cs = v @ v.T; A = v.shape[0]
        out[s] = float((cs.sum() - A) / (A * (A - 1)))
    return out

clip = rep_styles("clip_v2"); enc = rep_styles("opentma_h3d_v2")
gens = {"MLD": gen_styles("mld_v2"), "MDM": gen_styles("mdm_v2"), "T2M-GPT": gen_styles("t2mgpt_v2")}
oenc = {n: float(np.mean(list(rep_styles(m).values())))
        for m, n in [("opentma_unimocap_v2", "UniMoCap"), ("opentma_motionx_v2", "Motion-X")]}
styles = list(clip.keys())

# geometry: x stages, y = consistency 0..0.8 -> 0..6.4cm
X = {"clip": 0.0, "enc": 4.2, "MLD": 8.2, "MDM": 10.0, "T2M-GPT": 11.8}
fy = lambda v: v / 0.8 * 6.4
stats = lambda d: (min(d.values()), max(d.values()), float(np.mean(list(d.values()))))
c_lo, c_hi, c_m = stats(clip); e_lo, e_hi, e_m = stats(enc)

L = ["% cascade.tex, generated by eval/viz/make_cascade_tikz.py (band layout)"]
L.append(r"\begin{tikzpicture}[font=\small, line cap=round]")
for n, rgb in [("okblue", "0,114,178"), ("okskyblue", "86,180,233"),
               ("okgreen", "0,158,115"), ("okorange", "230,159,0"),
               ("okgrey", "120,130,150")]:
    L.append(f"\\definecolor{{{n}}}{{RGB}}{{{rgb}}}")
# y axis
L.append(f"\\draw[black!70, line width=0.4pt] (-0.15,0) -- (-0.15,{fy(0.8):.2f});")
for v in [0, 0.2, 0.4, 0.6, 0.8]:
    L.append(f"\\draw[black!55, line width=0.35pt] (-0.15,{fy(v):.2f}) -- (-0.27,{fy(v):.2f}) node[left, font=\\scriptsize] {{{v}}};")
    L.append(f"\\draw[black!7, line width=0.35pt] (-0.05,{fy(v):.2f}) -- ({X['T2M-GPT'] + 0.4:.2f},{fy(v):.2f});")
L.append(f"\\node[rotate=90, font=\\small] at (-1.05,{fy(0.4):.2f}) {{style-direction consistency $\\mathcal{{C}}$}};")
# stage 0 -> 1 band (min-max over styles) and mean line
L.append(f"\\fill[okgrey!16] ({X['clip']},{fy(c_lo):.2f}) -- ({X['enc']},{fy(e_lo):.2f}) -- ({X['enc']},{fy(e_hi):.2f}) -- ({X['clip']},{fy(c_hi):.2f}) -- cycle;")
L.append(f"\\draw[black, line width=2.1pt] ({X['clip']},{fy(c_m):.2f}) -- ({X['enc']},{fy(e_m):.2f});")
# branch bands first (so no band covers a line), then all lines and markers
for g, c in GCOL.items():
    g_lo, g_hi, g_m = stats(gens[g])
    L.append(f"\\fill[{c}!14] ({X['enc']},{fy(e_lo):.2f}) -- ({X[g]},{fy(max(g_lo, -0.02)):.2f}) -- ({X[g]},{fy(g_hi):.2f}) -- ({X['enc']},{fy(e_hi):.2f}) -- cycle;")
for g, c in GCOL.items():
    g_lo, g_hi, g_m = stats(gens[g])
    L.append(f"\\draw[{c}, line width=1.9pt] ({X['enc']},{fy(e_m):.2f}) -- ({X[g]},{fy(g_m):.2f});")
    L.append(f"\\fill[{c}] ({X[g]},{fy(g_m):.2f}) circle (0.10);")
    L.append(f"\\draw[{c}, line width=1.0pt, fill=white] ({X[g]},{fy(CORR[g]):.2f}) circle (0.10);")
    L.append(f"\\node[font=\\small\\bfseries, {c}!80!black, below=14pt] at ({X[g]},0) {{{g}}};")
# stage means and endpoints
L.append(f"\\fill[okblue] ({X['clip']},{fy(c_m):.2f}) circle (0.11) node[above=5pt, font=\\scriptsize, black] {{$0.64$}};")
L.append(f"\\fill[okgrey] ({X['enc']},{fy(e_m):.2f}) circle (0.11) node[above=5pt, font=\\scriptsize, black] {{$0.15$}};")
for n, v in oenc.items():
    L.append(f"\\draw[okgrey, line width=1.0pt, fill=white] ({X['enc'] - 0.075:.2f},{fy(v) - 0.075:.2f}) rectangle ({X['enc'] + 0.075:.2f},{fy(v) + 0.075:.2f});")
    L.append(f"\\node[font=\\scriptsize, okgrey!80!black, anchor=west] at ({X['enc'] + 0.16:.2f},{fy(v):.2f}) {{{n}}};")
L.append(f"\\node[font=\\small\\bfseries, okblue, below=14pt] at ({X['clip']},0) {{CLIP (input)}};")
L.append(f"\\node[font=\\small\\bfseries, okgrey!85!black, below=14pt] at ({X['enc']},0) {{alignment (TMA H3D)}};")
# legend
L.append(f"\\fill[okgrey!25] ({X['enc'] + 0.6:.2f},{fy(0.66):.2f}) rectangle ({X['enc'] + 1.0:.2f},{fy(0.70):.2f});")
L.append(f"\\node[anchor=west, font=\\scriptsize] at ({X['enc'] + 1.1:.2f},{fy(0.68):.2f}) {{range over the 13 styles}};")
L.append(f"\\draw[black!60, line width=1.0pt, fill=white] ({X['enc'] + 0.8:.2f},{fy(0.60):.2f}) circle (0.10);")
L.append(f"\\node[anchor=west, font=\\scriptsize] at ({X['enc'] + 1.1:.2f},{fy(0.60):.2f}) {{noise-corrected mean}};")
L.append(r"\end{tikzpicture}")
(ROOT.parent / "overleaf/figures/cascade.tex").write_text("\n".join(L) + "\n")
print("wrote cascade.tex (band)")
