"""Emit overleaf/figures/engram_bars.tex: dumbbell layout. One row per
generator; x = style-axis coherence. Per row: between-style baseline tick,
open circle = random-weight control, filled circle = engram within-style,
the segment between them = trained-weight excess (labelled), vermillion
square = activation consistency. CLIP reference as dashed line."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONS = {"MLD": 0.059, "MDM": 0.040, "T2M-GPT": 0.004}
CTRL = {"MLD": 0.145, "MDM": 0.260, "T2M-GPT": 0.145}
CLIP = 0.644
ORDER = ["MLD", "MDM", "T2M-GPT"]
COLROW = {"MLD": "okskyblue", "MDM": "okgreen", "T2M-GPT": "okorange"}
eng = {m: json.load(open(ROOT / f"results/engram_overlap_{k}.json"))
       for k, m in [("mld", "MLD"), ("mdm", "MDM"), ("t2mgpt", "T2M-GPT")]}

W = 10.6            # x scale: coherence 0..0.72 -> 0..W cm
fx = lambda v: v / 0.72 * W
RH = 1.5            # row spacing

L = ["% engram_bars.tex, generated by eval/viz/make_engram_tikz.py (dumbbell layout)"]
L.append(r"\begin{tikzpicture}[font=\small, line cap=round]")
for n, rgb in [("okblue", "0,114,178"), ("okskyblue", "86,180,233"),
               ("okgreen", "0,158,115"), ("okorange", "230,159,0"),
               ("okverm", "213,94,0")]:
    L.append(f"\\definecolor{{{n}}}{{RGB}}{{{rgb}}}")
H = (len(ORDER) - 1) * RH
# x axis
L.append(f"\\draw[black!70, line width=0.4pt] (0,{-0.75}) -- ({W:.2f},{-0.75});")
for v in [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]:
    L.append(f"\\draw[black!55, line width=0.35pt] ({fx(v):.2f},-0.75) -- ({fx(v):.2f},-0.85) node[below, font=\\scriptsize] {{{v}}};")
    L.append(f"\\draw[black!7, line width=0.35pt] ({fx(v):.2f},-0.65) -- ({fx(v):.2f},{H + 0.55:.2f});")
L.append(f"\\node[below=16pt, font=\\small] at ({W/2:.2f},-0.75) {{style-axis coherence}};")
# CLIP reference
L.append(f"\\draw[okblue, dash pattern=on 3pt off 2pt, line width=0.7pt] ({fx(CLIP):.2f},-0.65) -- ({fx(CLIP):.2f},{H + 0.55:.2f});")
L.append(f"\\node[font=\\scriptsize, okblue, anchor=south, rotate=90] at ({fx(CLIP) + 0.28:.2f},{H/2 - 0.6:.2f}) {{CLIP input consistency $0.64$}};")
for i, m in enumerate(ORDER):
    y = H - i * RH
    c = COLROW[m]
    w_in = eng[m]["within_style_mean"]; b = max(eng[m]["between_style_mean"], 0.0)
    exc = w_in - CTRL[m]
    L.append(f"\\node[anchor=east, font=\\small\\bfseries, {c}!75!black] at (-0.25,{y:.2f}) {{{m}}};")
    # excess segment (the finding), drawn under the markers
    L.append(f"\\draw[{c}, line width=2.6pt, opacity=0.45] ({fx(CTRL[m]):.3f},{y:.2f}) -- ({fx(w_in):.3f},{y:.2f});")
    # between-style baseline tick
    L.append(f"\\draw[black, line width=1.4pt] ({fx(b):.3f},{y - 0.14:.2f}) -- ({fx(b):.3f},{y + 0.14:.2f});")
    # activation consistency square
    L.append(f"\\fill[okverm] ({fx(CONS[m]) - 0.075:.3f},{y - 0.075:.2f}) rectangle ({fx(CONS[m]) + 0.075:.3f},{y + 0.075:.2f});")
    # control open circle, within filled circle
    L.append(f"\\draw[{c}, line width=1.1pt, fill=white] ({fx(CTRL[m]):.3f},{y:.2f}) circle (0.105);")
    L.append(f"\\fill[{c}] ({fx(w_in):.3f},{y:.2f}) circle (0.105);")
    # excess label above the segment midpoint
    mid = (CTRL[m] + w_in) / 2
    sign = "+" if exc >= 0 else ""
    L.append(f"\\node[font=\\scriptsize, {c}!70!black, above=3pt] at ({fx(mid):.3f},{y:.2f}) {{{sign}{exc:.2f} trained-weight excess}};")
# legend row
ly = H + 1.05
items = [
    (f"\\fill[okverm] (0,-0.075) rectangle (0.15,0.075);", "activations: consistency $\\mathcal{C}$"),
    (f"\\draw[black!60, line width=1.1pt, fill=white] (0.07,0) circle (0.105);", "random-weight control"),
    (f"\\fill[black!60] (0.07,0) circle (0.105);", "engram within-style $\\rho$"),
    (f"\\draw[black, line width=1.4pt] (0.07,-0.14) -- (0.07,0.14);", "between-style baseline"),
]
x0 = 0.0
for glyph, lab in items:
    L.append(f"\\begin{{scope}}[shift={{({x0:.2f},{ly:.2f})}}]")
    L.append(glyph)
    L.append(f"\\node[anchor=west, font=\\scriptsize] at (0.22,0) {{{lab}}};")
    L.append(r"\end{scope}")
    x0 += 2.75
L.append(r"\end{tikzpicture}")
(ROOT.parent / "overleaf/figures/engram_bars.tex").write_text("\n".join(L) + "\n")
print("wrote engram_bars.tex (dumbbell)")
