"""Emit overleaf/figures/flow_decoherence.{tex,dat files} — TikZ/pgfplots
version of the style-flow decoherence figure, computed from the REAL
measured latents (v1 8x7 grid, PCA plane, RBF-interpolated coherence),
same computation as make_landscape.py. Panels: CLIP / MDM / T2M-GPT."""
import numpy as np
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT.parent / "overleaf" / "figures"
GRID_N = 56          # coherence surf resolution per panel
ARROW_N = 7          # arrows per side

def load(model):
    root = ROOT / "results" / model
    sub = root / "0" if (root / "0").exists() else root
    Z_S = np.load(sub / "Z_S.npy"); Z_T = np.load(sub / "Z_T.npy")
    meta = json.load(open(sub / "meta.json")) if (sub / "meta.json").exists() else {}
    if Z_T.ndim == 2:
        Z_T = Z_T.reshape(-1, Z_S.shape[0], Z_S.shape[1])
    return Z_S, Z_T, meta

def pca2(Z_S, Z_T):
    X = np.vstack([Z_S] + [Z_T[j] for j in range(Z_T.shape[0])])
    mu = X.mean(0); X = X - mu
    _, _, Vt = np.linalg.svd(X, full_matrices=False)
    return lambda Z: (Z - mu) @ Vt[:2].T

def rbf_field(roots, vecs, XX, YY, sigma=None):
    if sigma is None:
        d = np.linalg.norm(roots[:, None] - roots[None], axis=-1)
        sigma = np.median(d[d > 0]) * 0.45
    P = np.stack([XX.ravel(), YY.ravel()], 1)
    w = np.exp(-((P[:, None] - roots[None]) ** 2).sum(-1) / (2 * sigma ** 2))
    wsum = w.sum(1, keepdims=True) + 1e-12
    V = (w @ vecs) / wsum
    n = np.linalg.norm(vecs, axis=1, keepdims=True) + 1e-12
    U = vecs / n
    Vu = (w @ U) / wsum
    coh = np.linalg.norm(Vu, axis=1)
    return V[:, 0].reshape(XX.shape), V[:, 1].reshape(XX.shape), coh.reshape(XX.shape)

def escapes(Z_S, Z_T):
    # cosine nearest-prototype, matching the paper's BER definition
    Zs = Z_S / (np.linalg.norm(Z_S, axis=1, keepdims=True) + 1e-8)
    n = 0
    for j in range(Z_T.shape[0]):
        Zt = Z_T[j] / (np.linalg.norm(Z_T[j], axis=1, keepdims=True) + 1e-8)
        n += int(((Zt @ Zs.T).argmax(1) != np.arange(Z_S.shape[0])).sum())
    return n, Z_T.shape[0] * Z_S.shape[0]

panels = []
for model, label in [("clip", "CLIP (input)"), ("mdm", "MDM"), ("t2mgpt", "T2M-GPT")]:
    Z_S, Z_T, meta = load(model)
    proj = pca2(Z_S, Z_T)
    P_S = proj(Z_S)
    roots = np.vstack([P_S] * Z_T.shape[0])
    vecs = np.vstack([proj(Z_T[j]) - P_S for j in range(Z_T.shape[0])])
    pad = 0.22 * (P_S.max(0) - P_S.min(0))
    x0, x1 = P_S[:, 0].min() - pad[0], P_S[:, 0].max() + pad[0]
    y0, y1 = P_S[:, 1].min() - pad[1], P_S[:, 1].max() + pad[1]
    # normalize panel coords to [0,1]^2 so panels share axes cleanly
    nx = lambda x: (x - x0) / (x1 - x0)
    ny = lambda y: (y - y0) / (y1 - y0)
    xs = np.linspace(x0, x1, GRID_N); ys = np.linspace(y0, y1, GRID_N)
    XX, YY = np.meshgrid(xs, ys)
    U, V, coh = rbf_field(roots, vecs, XX, YY)
    with open(OUT / f"flowdec_surf_{model}.dat", "w") as f:
        f.write("x y coh\n")
        for iy in range(GRID_N):
            for ix in range(GRID_N):
                f.write(f"{nx(XX[iy,ix]):.4f} {ny(YY[iy,ix]):.4f} {coh[iy,ix]:.4f}\n")
            f.write("\n")
    # arrows on a coarse grid, direction from interpolated field, fixed length
    axs = np.linspace(x0 + 0.09*(x1-x0), x1 - 0.09*(x1-x0), ARROW_N)
    ays = np.linspace(y0 + 0.09*(y1-y0), y1 - 0.09*(y1-y0), ARROW_N)
    AX, AY = np.meshgrid(axs, ays)
    AU, AV, _ = rbf_field(roots, vecs, AX, AY)
    L = 0.055
    with open(OUT / f"flowdec_arrows_{model}.dat", "w") as f:
        f.write("x y u v\n")
        for iy in range(ARROW_N):
            for ix in range(ARROW_N):
                a = np.arctan2(AV[iy,ix], AU[iy,ix])
                f.write(f"{nx(AX[iy,ix]):.4f} {ny(AY[iy,ix]):.4f} {L*np.cos(a):.4f} {L*np.sin(a)/((x1-x0)/(y1-y0)+1e-9)*((x1-x0)/(y1-y0)):.4f}\n")
    n_esc, n_tot = escapes(Z_S, Z_T)
    acts = [a.replace("a person is ", "") for a in meta.get("actions", [])]
    pos = [(nx(P_S[i,0]), ny(P_S[i,1])) for i in range(P_S.shape[0])]
    panels.append((model, label, n_esc, n_tot, acts, pos))

# emit the tikz file
T = ["% flow_decoherence.tex -- generated by eval/viz/make_flow_tikz.py from real latents."]
T.append(r"\begin{tikzpicture}[font=\small]")
T.append(r"\definecolor{okvermillion}{RGB}{213,94,0}")
T.append(r"""\tikzset{
  flowarrow/.style={-{Stealth[length=2.6pt, width=2.2pt]}, black!80, line width=0.75pt},
  flowhalo/.style={-{Stealth[length=2.6pt, width=2.2pt]}, white, line width=1.6pt},
  basindot/.style={circle, fill=white, draw=black, line width=0.6pt, inner sep=1.5pt},
  basinlabel/.style={font=\scriptsize, inner sep=1.3pt, rounded corners=1pt,
    fill=white, fill opacity=0.85, text opacity=1},
}""")
T.append(r"\begin{groupplot}[")
T.append(r"  group style={group size=3 by 1, horizontal sep=5mm},")
T.append(r"  width=5.35cm, height=5.35cm, view={0}{90},")
T.append(r"  xmin=0, xmax=1, ymin=0, ymax=1, enlargelimits=false,")
T.append(r"  xtick=\empty, ytick=\empty,")
T.append(r"  axis line style={black!55, line width=0.4pt},")
T.append(r"  colormap={muted}{rgb255=(48,56,100) rgb255=(108,122,158) rgb255=(206,196,170) rgb255=(230,159,0)},")
T.append(r"  point meta min=0, point meta max=1,")
T.append(r"  title style={font=\small, yshift=0pt}, clip mode=individual,]")
for k, (model, label, n_esc, n_tot, acts, pos) in enumerate(panels):
    cb = ""
    if k == 2:
        cb = (r"""colorbar, colorbar style={width=2.6mm,
      ylabel={directional coherence of the style flow}, ylabel style={font=\scriptsize},
      ytick={0,0.5,1}, yticklabels={0 (turbulent),0.5,1 (laminar)},
      tick label style={font=\scriptsize}},""")
    T.append(f"\\nextgroupplot[title={{{label} \\, {n_esc}/{n_tot} escapes}},{cb}]")
    T.append(f"\\addplot3[surf, shader=interp, z buffer=none] table[x=x, y=y, z=coh] {{figures/flowdec_surf_{model}.dat}};")
    for sty in ("flowhalo", "flowarrow"):
        T.append(f"\\addplot3[quiver={{u=\\thisrow{{u}}, v=\\thisrow{{v}}, w=0, every arrow/.append style={{{sty}}}}}] table[x=x, y=y, z expr=2] {{figures/flowdec_arrows_{model}.dat}};")
    for (a, (px, py)) in zip(acts, pos):
        T.append(f"\\node[basindot] at (axis cs:{px:.3f},{py:.3f},3) {{}};")
    # label 3 actions chosen to be maximally spread in the panel
    import itertools
    best, idx = -1, [0]
    if len(acts) >= 3:
        for c in itertools.combinations(range(len(acts)), 3):
            P = np.array([pos[i] for i in c])
            d = np.linalg.norm(P[:, None] - P[None], axis=-1).sum()
            if d > best:
                best, idx = d, list(c)
    for i in idx:
        px, py = pos[i]
        anch = "north" if py > 0.5 else "south"
        T.append(f"\\node[basinlabel, anchor={anch}] at (axis cs:{px:.3f},{py + (0.045 if anch=='south' else -0.045):.3f},3) {{{acts[i]}}};")
T.append(r"\end{groupplot}")
T.append(r"\end{tikzpicture}")
(OUT / "flow_decoherence.tex").write_text("\n".join(T) + "\n")
print("wrote flow_decoherence.tex + 6 dat files")
