"""Emit overleaf/figures/plane_two_axes.tex — pure-TikZ invariance-equivariance
plane, our design (shaded corner regions, sd error bars, noise-corrected open
circles joined by a thin stem). Data read from results/*_v2 reports."""
import json
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORRECTED = {"MDM": 0.102, "MLD": 0.162}  # T2M-GPT: 0.009 ~ raw, omitted (caption notes it)

def seed_stats(model):
    ss = json.load(open(ROOT / f"results/{model}/seed_summary.json"))["per_run"]
    ck = [r["cka"] for sd in ss.values() for r in sd.values()]
    co = [r["consistency"] for sd in ss.values() for r in sd.values()]
    return np.mean(ck), np.std(ck), np.mean(co), np.std(co)

pts = {n: seed_stats(m) for m, n in [("t2mgpt_v2", "T2M-GPT"), ("mdm_v2", "MDM"), ("mld_v2", "MLD")]}
r = json.load(open(ROOT / "results/clip_v2/report.json"))
pts["CLIP"] = (r["cka_mean"], 0.0, r["consistency_mean"], 0.0)
tma = {}
for label, dirn in [("HumanML3D", "opentma_h3d_v2"), ("UniMoCap", "opentma_unimocap_v2"),
                    ("Motion-X", "opentma_motionx_v2")]:
    rr = json.load(open(ROOT / f"results/{dirn}/report.json"))
    tma[label] = (rr["cka_mean"], rr["consistency_mean"])

# axis mapping: x in [0.55,1.0] -> [0,10.4]cm, y in [-0.02,0.73] -> [0,7.0]cm
X0, X1, W = 0.55, 1.00, 10.4
Y0, Y1, H = -0.02, 0.73, 7.0
fx = lambda x: (x - X0) / (X1 - X0) * W
fy = lambda y: (y - Y0) / (Y1 - Y0) * H

L = []
L.append("% plane_two_axes.tex -- generated by eval/viz/make_plane_tikz.py. Regenerate, don't hand-edit data.")
L.append(r"\begin{tikzpicture}[font=\small, line cap=round]")
for n, rgb in [("okpurple", "0,114,178"), ("okblue", "86,180,233"), ("okteal", "0,158,115"),
               ("okolive", "230,159,0"), ("okgreen", "0,158,115"), ("okorange", "230,159,0"),
               ("okvermillion", "213,94,0")]:
    L.append(f"\\definecolor{{{n}}}{{RGB}}{{{rgb}}}")
Col = {"CLIP": "okpurple", "MLD": "okblue", "MDM": "okteal", "T2M-GPT": "okolive"}
# corner regions (our rounded-rectangle design)
L.append(f"\\fill[okgreen!9, rounded corners=8pt] ({fx(0.905):.2f},{fy(0.55):.2f}) rectangle ({fx(1.0):.2f},{fy(0.73):.2f});")
L.append(f"\\fill[okorange!12, rounded corners=8pt] ({fx(0.905):.2f},{fy(-0.02):.2f}) rectangle ({fx(1.0):.2f},{fy(0.21):.2f});")
L.append(f"\\fill[okvermillion!9, rounded corners=8pt] ({fx(0.55):.2f},{fy(-0.02):.2f}) rectangle ({fx(0.78):.2f},{fy(0.16):.2f});")
L.append(f"\\node[anchor=north east, font=\\small\\itshape, okgreen] at ({fx(0.998):.2f},{fy(0.725):.2f}) {{factored}};")
L.append(f"\\node[anchor=south east, font=\\small\\itshape, okorange!80!black] at ({fx(0.998):.2f},{fy(-0.012):.2f}) {{structure only}};")
L.append(f"\\node[anchor=south west, font=\\small\\itshape, okvermillion!80!black] at ({fx(0.615):.2f},{fy(-0.012):.2f}) {{scrambled}};")
L.append(f"\\node[anchor=north west, font=\\small\\itshape, black!35] at ({fx(0.556):.2f},{fy(0.725):.2f}) {{(empty)}};")
# axes
L.append(f"\\draw[black!70, line width=0.4pt, ->] (0,0) -- ({W+0.25:.2f},0) node[below left=2pt, font=\\small, black] {{}};")
L.append(f"\\draw[black!70, line width=0.4pt, ->] (0,0) -- (0,{H+0.25:.2f});")
for xv in np.arange(0.55, 1.001, 0.05):
    L.append(f"\\draw[black!65, line width=0.35pt] ({fx(xv):.2f},0) -- ({fx(xv):.2f},-0.09) node[below, font=\\footnotesize] {{{xv:.2f}}};")
for yv in np.arange(0.0, 0.71, 0.1):
    L.append(f"\\draw[black!65, line width=0.35pt] (0,{fy(yv):.2f}) -- (-0.09,{fy(yv):.2f}) node[left, font=\\footnotesize] {{{yv:.1f}}};")
    L.append(f"\\draw[black!8, line width=0.3pt] (0,{fy(yv):.2f}) -- ({W:.2f},{fy(yv):.2f});")
L.append(f"\\node[below=22pt, font=\\small] at ({W/2:.2f},0) {{relational invariance (mean CKA)}};")
L.append(f"\\node[rotate=90, font=\\small] at (-1.0,{H/2:.2f}) {{directional equivariance (consistency)}};")
# TMA encoder squares
off = {"HumanML3D": ("right", 0.14, -0.12), "UniMoCap": ("left", -0.14, 0.0), "Motion-X": ("left", -0.14, 0.10)}
for label, (cx, cy) in tma.items():
    x, y = fx(cx), fy(cy)
    L.append(f"\\fill[okblue!70] ({x-0.075:.2f},{y-0.075:.2f}) rectangle ({x+0.075:.2f},{y+0.075:.2f});")
    side, dx, dy = off[label]
    anch = "west" if side == "right" else "east"
    L.append(f"\\node[anchor={anch}, font=\\footnotesize, okblue!80!black] at ({x+dx:.2f},{y+dy:.2f}) {{TMA {label}}};")
# generators + CLIP
lab = {"CLIP": ("east", -0.16, 0.0), "MLD": ("west", 0.18, -0.18), "MDM": ("west", 0.16, 0.05), "T2M-GPT": ("south", 0.0, 0.30)}
for name, (cx, sx, cy, sy) in pts.items():
    x, y, c = fx(cx), fy(cy), Col[name]
    if sy > 0:  # error bar
        L.append(f"\\draw[{c}, line width=0.8pt] ({x:.2f},{fy(cy-sy):.2f}) -- ({x:.2f},{fy(cy+sy):.2f});")
    L.append(f"\\fill[{c}] ({x:.2f},{y:.2f}) circle (0.10);")
    if name in CORRECTED:   # stem + open circle (our design: stem, no arrowhead)
        yc = fy(CORRECTED[name])
        L.append(f"\\draw[{c}!60, line width=0.5pt] ({x:.2f},{y:.2f}) -- ({x:.2f},{yc:.2f});")
        L.append(f"\\draw[{c}, line width=0.9pt, fill=white] ({x:.2f},{yc:.2f}) circle (0.10);")
    anch, dx, dy = lab[name]
    L.append(f"\\node[anchor={anch}, font=\\footnotesize\\bfseries, {c}] at ({x+dx:.2f},{y+dy:.2f}) {{{name}}};")
# legend
lx, ly = fx(0.565), fy(0.56)
L.append(f"\\fill[black] ({lx:.2f},{ly:.2f}) circle (0.08); \\node[anchor=west, font=\\scriptsize] at ({lx+0.16:.2f},{ly:.2f}) {{raw}};")
L.append(f"\\draw[black, line width=0.8pt, fill=white] ({lx:.2f},{ly-0.42:.2f}) circle (0.09); \\node[anchor=west, font=\\scriptsize] at ({lx+0.16:.2f},{ly-0.42:.2f}) {{noise-corrected (App.\\,C)}};")
L.append(r"\end{tikzpicture}")
(ROOT.parent / "overleaf/figures/plane_two_axes.tex").write_text("\n".join(L) + "\n")
print("wrote plane_two_axes.tex")
