"""Emit overleaf/figures/forest.tex — TikZ per-style escape forest,
matching the paper's authored-figure standard. Data: bayes_escape_summary."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COL = {"clip_v2": ("mindigo", "CLIP"), "mld_v2": ("mblue", "MLD"),
       "mdm_v2": ("msage", "MDM"), "t2mgpt_v2": ("mamber", "T2M-GPT")}
OFF = {"clip_v2": 0.30, "mld_v2": 0.10, "mdm_v2": -0.10, "t2mgpt_v2": -0.30}

d = json.load(open(ROOT / "results/bayes_escape_summary.json"))
styles = sorted(d["clip_v2"], key=lambda s: d["t2mgpt_v2"][s]["mean"], reverse=True)
W, RH = 8.6, 0.46                    # x-scale (prob 0..0.9 -> 0..W cm), row height
fx = lambda v: v / 0.9 * W

L = ["% forest.tex -- generated by eval/viz/make_forest_tikz.py"]
L.append(r"\begin{tikzpicture}[font=\small, line cap=round]")
for n, rgb in [("mindigo", "0,114,178"), ("mblue", "86,180,233"),
               ("msage", "0,158,115"), ("mamber", "230,159,0")]:
    L.append(f"\\definecolor{{{n}}}{{RGB}}{{{rgb}}}")
H = len(styles) * RH
for i, s in enumerate(styles):
    y = (len(styles) - 1 - i) * RH
    if i % 2 == 0:
        L.append(f"\\fill[black!4] (-0.05,{y - RH/2:.2f}) rectangle ({W + 0.05:.2f},{y + RH/2:.2f});")
    L.append(f"\\node[anchor=east, font=\\scriptsize] at (-0.15,{y:.2f}) {{{s}}};")
    for m, (c, _) in COL.items():
        e = d[m][s]
        yy = y + OFF[m] * RH
        L.append(f"\\draw[{c}, line width=0.9pt] ({fx(e['hdi94'][0]):.3f},{yy:.3f}) -- ({fx(e['hdi94'][1]):.3f},{yy:.3f});")
        L.append(f"\\fill[{c}] ({fx(e['mean']):.3f},{yy:.3f}) circle (1.3pt);")
# axis
L.append(f"\\draw[black!70, line width=0.4pt] (0,{-RH/2 - 0.12:.2f}) -- ({W:.2f},{-RH/2 - 0.12:.2f});")
for v in [0, 0.2, 0.4, 0.6, 0.8]:
    L.append(f"\\draw[black!55, line width=0.35pt] ({fx(v):.2f},{-RH/2 - 0.12:.2f}) -- ({fx(v):.2f},{-RH/2 - 0.22:.2f}) node[below, font=\\scriptsize] {{{v}}};")
L.append(f"\\node[below=14pt, font=\\small] at ({W/2:.2f},{-RH/2 - 0.12:.2f}) {{posterior escape probability (mean, $94\\%$ HDI)}};")
# legend row above
lx = 0.1
for m, (c, name) in COL.items():
    L.append(f"\\draw[{c}, line width=0.9pt] ({lx:.2f},{H + 0.18:.2f}) -- ({lx + 0.34:.2f},{H + 0.18:.2f});")
    L.append(f"\\fill[{c}] ({lx + 0.17:.2f},{H + 0.18:.2f}) circle (1.3pt);")
    L.append(f"\\node[anchor=west, font=\\scriptsize, {c}] at ({lx + 0.40:.2f},{H + 0.18:.2f}) {{{name}}};")
    lx += 2.05
L.append(r"\end{tikzpicture}")
(ROOT.parent / "overleaf/figures/forest.tex").write_text("\n".join(L) + "\n")
print("wrote forest.tex")
