"""Emit overleaf/figures/style_fan.tex — pure TikZ version of the style cone.
Rays are the REAL angles of each style vector delta_j(a) to its style's mean
direction (recomputed from results/*_v2 latents; generators seed-averaged).
90 deg (vertical) = the mean direction; horizontal = orthogonal = no axis."""
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COL = {"CLIP": "okpurple", "MLD": "okblue", "MDM": "okteal", "T2M-GPT": "okolive"}

def fan_angles(Z_S, Z_T):
    delta = Z_T - Z_S[None]
    out = []
    for j in range(delta.shape[0]):
        v = delta[j] / (np.linalg.norm(delta[j], axis=-1, keepdims=True) + 1e-9)
        mu = v.mean(0); mu /= (np.linalg.norm(mu) + 1e-9)
        out.append(np.degrees(np.arccos(np.clip(v @ mu, -1, 1))))
    return np.concatenate(out)

data = {}
zs = np.load(ROOT / "results/clip_v2/0/Z_S.npy")
zt = np.load(ROOT / "results/clip_v2/0/Z_T.npy")
data["CLIP"] = fan_angles(zs, zt.reshape(13, 24, -1) if zt.ndim == 2 else zt)
for m, name in [("mld_v2", "MLD"), ("mdm_v2", "MDM"), ("t2mgpt_v2", "T2M-GPT")]:
    ZS = np.stack([np.load(p / "Z_S.npy") for p in sorted(ROOT.glob(f"results/{m}/seed4*/0"))])
    ZT = np.stack([np.load(p / "Z_T.npy") for p in sorted(ROOT.glob(f"results/{m}/seed4*/0"))])
    data[name] = fan_angles(np.zeros_like(ZS[0]), (ZT - ZS[:, None]).mean(0))

rng = np.random.default_rng(0)
L = []
L.append("% style_fan.tex -- generated by eval/viz/make_fan_tikz.py from real latents. Do not hand-edit rays.")
L.append(r"\begin{tikzpicture}[line cap=round]")
L.append(r"\definecolor{okpurple}{RGB}{0,114,178}")
L.append(r"\definecolor{okblue}{RGB}{86,180,233}")
L.append(r"\definecolor{okteal}{RGB}{0,158,115}")
L.append(r"\definecolor{okolive}{RGB}{230,159,0}")
SEP = 4.4  # panel spacing (cm)
R = 1.55   # fan radius
for i, (name, angs) in enumerate(data.items()):
    x0 = i * SEP
    c = COL[name]
    med = float(np.median(angs))
    L.append(f"\\begin{{scope}}[shift={{({x0:.2f},0)}}]")
    # median cone (wedge around vertical)
    L.append(f"\\fill[{c}!14] (0,0) -- ({90-med:.1f}:{R:.2f}) arc ({90-med:.1f}:{90+med:.1f}:{R:.2f}) -- cycle;")
    # baseline (90deg-to-mean, i.e. horizontal) + reference spokes
    L.append(f"\\draw[black!35, line width=0.35pt] (-{R+0.12:.2f},0) -- ({R+0.12:.2f},0);")
    for a in (45, 135):
        L.append(f"\\draw[black!20, line width=0.3pt] (0,0) -- ({a}:{R+0.05:.2f});")
    # rays: fold each real angle to a random side of vertical
    sides = rng.choice([-1, 1], size=len(angs))
    for a, s in zip(angs, sides):
        th = 90 + s * float(a)
        L.append(f"\\draw[{c}, line width=0.5pt, opacity=0.5] (0,0) -- ({th:.2f}:{R*0.94:.2f});")
    # mean direction
    lab = " node[right=1pt, pos=0.85, font=\\scriptsize] {$\\bar{\\delta}_j$}" if i == 0 else ""
    L.append(f"\\draw[black, line width=1.1pt] (0,0) -- (90:{R+0.1:.2f}){lab};")
    # angle ticks
    L.append(f"\\node[font=\\tiny, black!55] at (37:{R+0.32:.2f}) {{$45^\\circ$}};")
    L.append(f"\\node[font=\\tiny, black!55] at (143:{R+0.32:.2f}) {{$45^\\circ$}};")
    L.append(f"\\node[font=\\tiny, black!55, anchor=west] at ({R+0.1:.2f},0) {{$90^\\circ$}};")
    L.append(f"\\node[font=\\tiny, black!55, anchor=east] at (-{R+0.1:.2f},0) {{$90^\\circ$}};")
    # title
    L.append(f"\\node[font=\\small\\bfseries, {c}, align=center] at (0,{R+0.92:.2f}) {{{name}}};")
    L.append(f"\\node[font=\\scriptsize, {c}!75!black] at (0,{R+0.58:.2f}) {{median ${med:.0f}^\\circ$}};")
    L.append(r"\end{scope}")
L.append(r"\end{tikzpicture}")
out = ROOT.parent / "overleaf/figures/style_fan.tex"
out.write_text("\n".join(L) + "\n")
print(f"wrote {out} ({len(L)} lines)")
